const mongoose = require('mongoose');

const storeSchema = new mongoose.Schema(
  {
    storeName: { type: String, default: 'NC' },
    array2d: {
      type: Array,
      default: [
        [
          {
            id: mongoose.Schema.Types.ObjectId,
            estate: { type: String, default: 'NC' },
            vintage: { type: String, default: 'NC' },
            cuvee: { type: String, default: 'NC' },
            stockStatus: 0,
            typeOfWine: { type: String, default: 'NC' },
            image: { type: String, default: 'NC' },
            price: { type: String, default: 'NC' },
            storeId: { type: Array, default: [] },
            storeIndex: { type: Array, default: [] },
          },
        ],
        [
          {
            id: mongoose.Schema.Types.ObjectId,
            estate: { type: String, default: 'NC' },
            vintage: { type: String, default: 'NC' },
            cuvee: { type: String, default: 'NC' },
            stockStatus: 0,
            typeOfWine: { type: String, default: 'NC' },
            image: { type: String, default: 'NC' },
            price: { type: String, default: 'NC' },
            storeId: { type: Array, default: [] },
            storeIndex: { type: Array, default: [] },
          },
          {
            id: mongoose.Schema.Types.ObjectId,
            estate: { type: String, default: 'NC' },
            vintage: { type: String, default: 'NC' },
            cuvee: { type: String, default: 'NC' },
            stockStatus: 0,
            typeOfWine: { type: String, default: 'NC' },
            image: { type: String, default: 'NC' },
            price: { type: String, default: 'NC' },
            storeId: { type: Array, default: [] },
            storeIndex: { type: Array, default: [] },
          },
        ],
        [
          {
            id: mongoose.Schema.Types.ObjectId,
            estate: { type: String, default: 'NC' },
            vintage: { type: String, default: 'NC' },
            cuvee: { type: String, default: 'NC' },
            stockStatus: 0,
            typeOfWine: { type: String, default: 'NC' },
            image: { type: String, default: 'NC' },
            price: { type: String, default: 'NC' },
            storeId: { type: Array, default: [] },
            storeIndex: { type: Array, default: [] },
          },
          {
            id: mongoose.Schema.Types.ObjectId,
            estate: { type: String, default: 'NC' },
            vintage: { type: String, default: 'NC' },
            cuvee: { type: String, default: 'NC' },
            stockStatus: 0,
            typeOfWine: { type: String, default: 'NC' },
            image: { type: String, default: 'NC' },
            price: { type: String, default: 'NC' },
            storeId: { type: Array, default: [] },
            storeIndex: { type: Array, default: [] },
          },
          {
            id: mongoose.Schema.Types.ObjectId,
            estate: { type: String, default: 'NC' },
            vintage: { type: String, default: 'NC' },
            cuvee: { type: String, default: 'NC' },
            stockStatus: 0,
            typeOfWine: { type: String, default: 'NC' },
            image: { type: String, default: 'NC' },
            price: { type: String, default: 'NC' },
            storeId: { type: Array, default: [] },
            storeIndex: { type: Array, default: [] },
          },
        ],
        [
          {
            id: mongoose.Schema.Types.ObjectId,
            estate: { type: String, default: 'NC' },
            vintage: { type: String, default: 'NC' },
            cuvee: { type: String, default: 'NC' },
            stockStatus: { type: Number, default: 0 },
            typeOfWine: { type: String, default: 'NC' },
            image: { type: String, default: 'NC' },
            price: { type: String, default: 'NC' },
            storeId: { type: Array, default: [] },
            storeIndex: { type: Array, default: [] },
          },

          {
            id: mongoose.Schema.Types.ObjectId,
            estate: { type: String, default: 'NC' },
            vintage: { type: String, default: 'NC' },
            cuvee: { type: String, default: 'NC' },
            stockStatus: { type: Number, default: 0 },
            typeOfWine: { type: String, default: 'NC' },
            image: { type: String, default: 'NC' },
            price: { type: String, default: 'NC' },
            storeId: { type: Array, default: [] },
            storeIndex: { type: Array, default: [] },
          },
          {
            id: mongoose.Schema.Types.ObjectId,
            estate: { type: String, default: 'NC' },
            vintage: { type: String, default: 'NC' },
            cuvee: { type: String, default: 'NC' },
            stockStatus: { type: Number, default: 0 },
            typeOfWine: { type: String, default: 'NC' },
            image: { type: String, default: 'NC' },
            price: { type: String, default: 'NC' },
            storeId: { type: Array, default: [] },
            storeIndex: { type: Array, default: [] },
          },
          {
            id: mongoose.Schema.Types.ObjectId,
            estate: { type: String, default: 'NC' },
            vintage: { type: String, default: 'NC' },
            cuvee: { type: String, default: 'NC' },
            stockStatus: { type: Number, default: 0 },
            typeOfWine: { type: String, default: 'NC' },
            image: { type: String, default: 'NC' },
            price: { type: String, default: 'NC' },
            storeId: { type: Array, default: [] },
            storeIndex: { type: Array, default: [] },
          },
        ],
        [
          {
            id: mongoose.Schema.Types.ObjectId,
            estate: { type: String, default: 'NC' },
            vintage: { type: String, default: 'NC' },
            cuvee: { type: String, default: 'NC' },
            stockStatus: { type: Number, default: 0 },
            typeOfWine: { type: String, default: 'NC' },
            image: { type: String, default: 'NC' },
            price: { type: String, default: 'NC' },
            storeId: { type: Array, default: [] },
            storeIndex: { type: Array, default: [] },
          },
          {
            id: mongoose.Schema.Types.ObjectId,
            estate: { type: String, default: 'NC' },
            vintage: { type: String, default: 'NC' },
            cuvee: { type: String, default: 'NC' },
            stockStatus: { type: Number, default: 0 },
            typeOfWine: { type: String, default: 'NC' },
            image: { type: String, default: 'NC' },
            price: { type: String, default: 'NC' },
            storeId: { type: Array, default: [] },
            storeIndex: { type: Array, default: [] },
          },

          {
            id: mongoose.Schema.Types.ObjectId,
            estate: { type: String, default: 'NC' },
            vintage: { type: String, default: 'NC' },
            cuvee: { type: String, default: 'NC' },
            stockStatus: { type: Number, default: 0 },
            typeOfWine: { type: String, default: 'NC' },
            image: { type: String, default: 'NC' },
            price: { type: String, default: 'NC' },
            storeId: { type: Array, default: [] },
            storeIndex: { type: Array, default: [] },
          },
          {
            id: mongoose.Schema.Types.ObjectId,
            estate: { type: String, default: 'NC' },
            vintage: { type: String, default: 'NC' },
            cuvee: { type: String, default: 'NC' },
            stockStatus: { type: Number, default: 0 },
            typeOfWine: { type: String, default: 'NC' },
            image: { type: String, default: 'NC' },
            price: { type: String, default: 'NC' },
            storeId: { type: Array, default: [] },
            storeIndex: { type: Array, default: [] },
          },
          {
            id: mongoose.Schema.Types.ObjectId,
            estate: { type: String, default: 'NC' },
            vintage: { type: String, default: 'NC' },
            cuvee: { type: String, default: 'NC' },
            stockStatus: { type: Number, default: 0 },
            typeOfWine: { type: String, default: 'NC' },
            image: { type: String, default: 'NC' },
            price: { type: String, default: 'NC' },
            storeId: { type: Array, default: [] },
            storeIndex: { type: Array, default: [] },
          },
        ],
      ],
    },
  },
  { timestamps: true }
);

module.exports = mongoose.model('Store', storeSchema);
